import { getCollection } from "astro:content";
import shellCssSource from "../styles/comic-shell.css?raw";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { locales, type Locale } from "./i18n";
import { localizedPath } from "./routes";

// Comic editions are complete HTML documents kept verbatim in src/comics/<id>/<locale>.html.
const editionSources = import.meta.glob<string>("/src/comics/*/*.html", { query: "?raw", import: "default", eager: true });
// Self-hosted @font-face rules generated by scripts/comics.mjs.
const fontSources = import.meta.glob<string>("/src/comics/*/fonts/*.css", { query: "?raw", import: "default", eager: true });

export interface ComicEdition {
  locale: Locale;
  title: string;
  description: string;
  html: string;
  fontCss: string;
  cover: { jpg: string; webp: string } | null;
}

export interface Comic {
  id: string;
  publishedAt: Date;
  updatedAt: Date;
  sourceLocale: Locale;
  editions: ComicEdition[];
}

export function comicPath(locale: Locale, id: string): string {
  return localizedPath(locale, `/comics/${id}`);
}

export function comicsIndexPath(locale: Locale): string {
  return localizedPath(locale, "/comics");
}

/** The edition to show a reader of `locale`: their language when it exists, else the original. */
export function editionFor(comic: Comic, locale: Locale): ComicEdition {
  return comic.editions.find((edition) => edition.locale === locale)
    ?? comic.editions.find((edition) => edition.locale === comic.sourceLocale)
    ?? comic.editions[0]!;
}

function coverFor(id: string, locale: Locale): ComicEdition["cover"] {
  const base = `/comics/${id}/covers/${locale}`;
  // Pages render from the project root, so public/ is resolved from the working directory.
  return existsSync(join(process.cwd(), "public", `${base}.jpg`)) && existsSync(join(process.cwd(), "public", `${base}.webp`))
    ? { jpg: `${base}.jpg`, webp: `${base}.webp` }
    : null;
}

/** Published comics, newest first. Drafts are only visible in `astro dev`. */
export async function getComics(): Promise<Comic[]> {
  const entries = await getCollection("comics", ({ data }) => !data.draft || import.meta.env.DEV);
  return entries
    .map((entry) => {
      const editions = locales.flatMap((locale): ComicEdition[] => {
        const meta = entry.data.editions[locale];
        const html = editionSources[`/src/comics/${entry.id}/${locale}.html`];
        if (!meta || !html) return [];
        const fontCss = (fontSources[`/src/comics/${entry.id}/fonts/${locale}.css`] ?? "").replace(/\/\*[\s\S]*?\*\//g, "").trim();
        return [{ locale, title: meta.title, description: meta.description, html, fontCss, cover: coverFor(entry.id, locale) }];
      });
      return {
        id: entry.id,
        publishedAt: entry.data.publishedAt,
        updatedAt: entry.data.updatedAt,
        sourceLocale: entry.data.sourceLocale,
        editions,
      };
    })
    .filter((comic) => comic.editions.length > 0)
    .sort((left, right) => right.publishedAt.valueOf() - left.publishedAt.valueOf());
}

// Same per-language system stacks as global.css, for the comic page header and footer.
const latinStack = 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif';
const shellFontStacks: Record<Locale, string> = {
  zh: '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei UI", "Microsoft YaHei", "Noto Sans CJK SC", "Source Han Sans SC", "Noto Sans SC", sans-serif',
  ja: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", "Hiragino Kaku Gothic ProN", "Yu Gothic UI", "Yu Gothic", Meiryo, "Noto Sans CJK JP", "Noto Sans JP", sans-serif',
  ko: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Apple SD Gothic Neo", "Malgun Gothic", "Noto Sans CJK KR", "Noto Sans KR", sans-serif',
  th: 'Thonburi, "Leelawadee UI", "Noto Sans Thai", ui-sans-serif, system-ui, sans-serif',
  en: latinStack,
  fr: latinStack,
  de: latinStack,
  vi: latinStack,
};

export function shellFontStack(locale: Locale): string {
  return shellFontStacks[locale];
}

/** comic-shell.css, minified once; it is inlined into two shadow roots on every comic page. */
export const shellCss = shellCssSource
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/\s+/g, " ")
  .replace(/\s*([{};,>])\s*/g, "$1")
  .replace(/;}/g, "}")
  .trim();
